name: Build & Deploy (by Hakyll)

on:
  push:
    branches:
      - master
      - dev
  # schedule:
  #   - cron: '* 17 * * *'
      # Liang-Ting (2023-04-28): Run this workflow every day at 1700 UTC, i.e. 0100 Taiwan Time.
jobs:
  build:
    strategy:
      matrix:
        ghc: [ '9.4.8' ]
        os: ['ubuntu-latest']
    env:
      FLAGS: "--flag hakyll:-previewServer --flag hakyll:-watchServer --flag hakyll:-checkexternal"

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: 'latest'

    - name: Cache dependencies and .stack-work
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: stack-${{ runner.OS }}-${{ hashFiles('stack.yaml') }}

    - name: Build dependencies and the site generator
      run: |
        stack build ${FLAGS}

    - name: Build the site
      env:
        # citeproc requires this locale environment variable.
        LANG: en_US.UTF-8
      run: |
        stack run -- site build
    - name: Check the site output
      run: |
        stack run -- site check --internal-links

    - uses: peaceiris/actions-gh-pages@v3
      name: Publish to the organsiation site      
      if: github.ref == 'refs/heads/master'
      with:
        # Type the following in the terminal to get private/public keys:
        #
        # ssh-keygen -t rsa -b 4096 -C "$(git config user.email)" -f gh-pages -N ""
        #
        # and add
        #
        #   1. the private key as a secrete ACTIONS_DEPLOY_KEY in the GitHub repo hosting the source code,
        #   2. the public key as a deploy key in the GitHub repo hosting the website.
        #
        # For details, see
        # https://github.com/marketplace/actions/github-pages-action
        #
        deploy_key: ${{ secrets.ACTION_DEPLOY_KEY_TO_TEAM_SITE }}

        # Ensure to match the source branch specified on the GitHub setting.
        #
        cname: flolac.iis.sinica.edu.tw
        external_repository: flolac-tw/flolac-tw.github.io
        publish_branch: master
        publish_dir: _site
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        
    - uses: peaceiris/actions-gh-pages@v3
      name: Publish to the project site
      if: github.ref == 'refs/heads/dev'
      with:
        # For details, see
        # https://github.com/marketplace/actions/github-pages-action
        #
        github_token: ${{ secrets.GITHUB_TOKEN }}

        # Ensure to match the source branch specified on the GitHub setting.
        #
        publish_dir: _site
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
